name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - if: matrix.os == 'ubuntu-latest'
      name: Update coverage report
      uses: ncruces/go-coverage-report@main
      continue-on-error: true
